# Generated by Django 3.1.4 on 2020-12-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_solicitudprestamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagoadelantado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cuota', models.FloatField(blank=True, null=True)),
                ('restante', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pagoadelantado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagoautomatico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cuenta', models.IntegerField(blank=True, null=True)),
                ('id_cuenta', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cuota', models.FloatField(blank=True, null=True)),
                ('restante', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pagoautomatico',
                'managed': False,
            },
        ),
    ]
