# Generated by Django 3.1.4 on 2021-01-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_planilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_cuenta', models.IntegerField(blank=True, null=True)),
                ('id_cuenta', models.IntegerField(blank=True, null=True)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('periodo_pago', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
    ]
