# Generated by Django 3.1.4 on 2020-12-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('nombre_portador', models.CharField(blank=True, max_length=100, null=True)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('autorizado', models.IntegerField(blank=True, null=True)),
                ('cobrado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cheque',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chequera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('cheques_disponibles', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chequera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clienteempresarial',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('nombre_representante', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clienteempresarial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clienteindividual',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('cui', models.BigIntegerField()),
                ('nit', models.IntegerField()),
                ('primer_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clienteindividual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('moneda', models.CharField(blank=True, max_length=1, null=True)),
                ('puntos', models.FloatField(blank=True, null=True)),
                ('cashback', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuentaahorro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fondo', models.FloatField(blank=True, null=True)),
                ('tasa_interes', models.FloatField(blank=True, null=True)),
                ('promocion', models.FloatField(blank=True, null=True)),
                ('moneda', models.CharField(blank=True, max_length=1, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('pre_auto', models.IntegerField(blank=True, null=True)),
                ('cheques_disponibles', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cuentaahorro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuentafija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuota', models.FloatField(blank=True, null=True)),
                ('capitalizacion', models.IntegerField(blank=True, null=True)),
                ('tasa_interes', models.FloatField(blank=True, null=True)),
                ('fondo_total', models.FloatField(blank=True, null=True)),
                ('moneda', models.CharField(blank=True, max_length=1, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cuentafija',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuentamonetaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fondo', models.FloatField(blank=True, null=True)),
                ('monto_manejo', models.FloatField(blank=True, null=True)),
                ('moneda', models.CharField(blank=True, max_length=1, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('pre_auto', models.IntegerField(blank=True, null=True)),
                ('cheques_disponibles', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cuentamonetaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depositante', models.IntegerField(blank=True, null=True)),
                ('receptor', models.IntegerField(blank=True, null=True)),
                ('tipo_receptor', models.IntegerField(blank=True, null=True)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('moneda', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'deposito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(blank=True, null=True)),
                ('modalidad_pago', models.IntegerField(blank=True, null=True)),
                ('interes', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prestamo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjetacredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('limite', models.FloatField(blank=True, null=True)),
                ('moneda', models.CharField(blank=True, max_length=1, null=True)),
                ('puntos', models.FloatField(blank=True, null=True)),
                ('porcentaje', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarjetacredito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjetadebito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_usuario', models.IntegerField()),
                ('fondo', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarjetadebito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=150, null=True)),
                ('contrasenia', models.CharField(blank=True, max_length=100, null=True)),
                ('tarjetas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
