# Generated by Django 3.1.4 on 2021-01-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_pagoadelantado_pagoautomatico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cuenta', models.IntegerField(blank=True, null=True)),
                ('id_cuenta', models.IntegerField(blank=True, null=True)),
                ('periodo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'planilla',
                'managed': False,
            },
        ),
    ]
